package com.papack.maceattackassistance.client.config;

import com.papack.maceattackassistance.client.ColorData;
import com.papack.maceattackassistance.client.config.Config;
import com.papack.maceattackassistance.client.config.ConfigOperation;
import me.shedaniel.clothconfig2.api.AbstractConfigListEntry;
import me.shedaniel.clothconfig2.api.ConfigBuilder;
import me.shedaniel.clothconfig2.api.ConfigCategory;
import me.shedaniel.clothconfig2.api.ConfigEntryBuilder;
import me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder;
import me.shedaniel.clothconfig2.impl.builders.IntSliderBuilder;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.util.Formatting;
import net.minecraft.text.Text;
import net.minecraft.client.gui.screen.Screen;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Environment(value=EnvType.CLIENT)
public class ModConfigScreen {
    public static Screen getConfigScreen(Screen parent) {
        ConfigBuilder builder = ConfigBuilder.create().setParentScreen(parent).setTitle((Text)Text.translatable((String)"config.mace_attack_assistance.title"));
        ConfigCategory attack = builder.getOrCreateCategory((Text)Text.literal((String)"Attack"));
        ConfigCategory jump = builder.getOrCreateCategory((Text)Text.literal((String)"Jump"));
        ConfigCategory refill = builder.getOrCreateCategory((Text)Text.literal((String)"AutoRefill"));
        ConfigCategory aim = builder.getOrCreateCategory((Text)Text.literal((String)"Aim"));
        ConfigCategory effects = builder.getOrCreateCategory((Text)Text.literal((String)"Effects,Marker"));
        ConfigCategory spiral = builder.getOrCreateCategory((Text)Text.literal((String)"SpiralMaker"));
        ConfigCategory color = builder.getOrCreateCategory((Text)Text.literal((String)"Spiral,Beam Color"));
        ConfigCategory fov = builder.getOrCreateCategory((Text)Text.literal((String)"Search Range,Angle"));
        ConfigCategory recon = builder.getOrCreateCategory((Text)Text.literal((String)"Recon"));
        ConfigCategory others = builder.getOrCreateCategory((Text)Text.literal((String)"Others"));
        ConfigEntryBuilder entryBuilder = builder.entryBuilder();
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.attack_assistance"), Config.ATTACK_ASSISTANCE).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ATTACK_ASSISTANCE)).setSaveConsumer(newValue -> {            Config.ATTACK_ASSISTANCE = newValue;        }).build());
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.weapon_swing"), Config.WEAPON_SWING).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_WEAPON_SWING)).setSaveConsumer(newValue -> {            Config.WEAPON_SWING = newValue;        }).build());
        attack.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.swing_toggle"), Config.SwingToggle.class, Config.SWING_TOGGLE).setDefaultValue(Config.SwingToggle.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SWING_TOGGLE))).setSaveConsumer(newValue -> {            Config.SWING_TOGGLE = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.swing_toggle")}).build());
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.return_to_prev_slot"), Config.RETURN_TO_PREV_SLOT).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_RETURN_TO_PREV_SLOT)).setSaveConsumer(newValue -> {            Config.RETURN_TO_PREV_SLOT = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.return_to_prev_slot")}).build());
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.hot_swap"), Config.HOT_SWAP).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_HOT_SWAP)).setSaveConsumer(newValue -> {            Config.HOT_SWAP = newValue;        }).build());
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.stun_slamming"), Config.STUN_SLAMMING).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_STUN_SLAMMING)).setSaveConsumer(newValue -> {            Config.STUN_SLAMMING = newValue;        }).build());
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.breach_swap"), Config.BREACH_SWAP).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_BREACH_SWAP)).setSaveConsumer(newValue -> {            Config.BREACH_SWAP = newValue;        }).build());
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.breach_limited"), Config.BREACH_LIMITED).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_BREACH_LIMITED)).setSaveConsumer(newValue -> {            Config.BREACH_LIMITED = newValue;        }).build());
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.breach_on_ground"), Config.BREACH_ON_GROUND).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_BREACH_ON_GROUND)).setSaveConsumer(newValue -> {            Config.BREACH_ON_GROUND = newValue;        }).build());
        attack.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.snapback"), Config.SNAPBACK).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SNAPBACK)).setSaveConsumer(newValue -> {            Config.SNAPBACK = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.snapback")}).build());
        attack.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.snapback_threshold"), Config.SNAPBACK_THRESHOLD, 4, 10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SNAPBACK_THRESHOLD)).setSaveConsumer(newValue -> {            Config.SNAPBACK_THRESHOLD = newValue;        }).build());
        attack.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Snapback - Tolerance"), Config.SNAPBACK_TOLERANCE, 0, 200).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SNAPBACK_TOLERANCE)).setSaveConsumer(newValue -> {            Config.SNAPBACK_TOLERANCE = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.snapback_tolerance")}).build());
        attack.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.axe_slot"), Config.AXE_SLOT + 1, 0, 9).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_AXE_SLOT) + 1).setSaveConsumer(newValue -> {            Config.AXE_SLOT = newValue - 1;        }).build());
        attack.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.mace_slot_primary"), Config.MACE_PRIMARY + 1, 0, 9).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_MACE_PRIMARY) + 1).setSaveConsumer(newValue -> {            Config.MACE_PRIMARY = newValue - 1;        }).build());
        attack.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.mace_slot_breach"), Config.MACE_BREACH + 1, 0, 9).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_MACE_BREACH) + 1).setSaveConsumer(newValue -> {            Config.MACE_BREACH = newValue - 1;        }).build());
        aim.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.aim_assist"), Config.AIM_ASSIST).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_AIM_ASSIST)).setSaveConsumer(newValue -> {            Config.AIM_ASSIST = newValue;        }).build());
        aim.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_villager"), Config.ALLOWED_VILLAGER).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ALLOWED_VILLAGER)).setSaveConsumer(newValue -> {            Config.ALLOWED_VILLAGER = newValue;        }).build());
        aim.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_iron_golem"), Config.ALLOWED_IRON_GOLEM).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ALLOWED_IRON_GOLEM)).setSaveConsumer(newValue -> {            Config.ALLOWED_IRON_GOLEM = newValue;        }).build());
        aim.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_hostile"), Config.ALLOWED_HOSTILE).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ALLOWED_HOSTILE)).setSaveConsumer(newValue -> {            Config.ALLOWED_HOSTILE = newValue;        }).build());
        aim.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_passive"), Config.ALLOWED_PASSIVE).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ALLOWED_PASSIVE)).setSaveConsumer(newValue -> {            Config.ALLOWED_PASSIVE = newValue;        }).build());
        aim.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_ambient"), Config.ALLOWED_AMBIENT).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ALLOWED_AMBIENT)).setSaveConsumer(newValue -> {            Config.ALLOWED_AMBIENT = newValue;        }).build());
        aim.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_player"), Config.ALLOWED_PLAYER).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ALLOWED_PLAYER)).setSaveConsumer(newValue -> {            Config.ALLOWED_PLAYER = newValue;        }).build());
        aim.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.max_speed_yaw"), Config.MAX_SPEED_YAW, 0, 15).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_MAX_SPEED_YAW)).setSaveConsumer(newValue -> {            Config.MAX_SPEED_YAW = newValue;        }).build());
        aim.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.aim_mode"), Config.AimMode.class, Config.AIM_MODE).setDefaultValue(Config.AimMode.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_AIM_MODE))).setSaveConsumer(newValue -> {            Config.AIM_MODE = newValue;        }).build());
        aim.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.auto_mode_threshold"), Config.AUTO_MODE_THRESHOLD, 10, 30).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_AUTO_MODE_THRESHOLD)).setSaveConsumer(newValue -> {            Config.AUTO_MODE_THRESHOLD = newValue;        }).build());
        jump.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.jump_assist"), Config.JUMP_ASSIST).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_JUMP_ASSIST)).setSaveConsumer(newValue -> {            Config.JUMP_ASSIST = newValue;        }).build());
        jump.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.wall_climbing"), Config.WALL_CLIMBING).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_WALL_CLIMBING)).setSaveConsumer(newValue -> {            Config.WALL_CLIMBING = newValue;        }).build());
        jump.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.toggle_elytra"), Config.TOGGLE_SLOT, 0, 9).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_TOGGLE_SLOT)).setSaveConsumer(newValue -> {            Config.TOGGLE_SLOT = newValue;        }).build());
        jump.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.rocket_blitz"), Config.ROCKET_BLITZ).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ROCKET_BLITZ)).setSaveConsumer(newValue -> {            Config.ROCKET_BLITZ = newValue;        }).build());
        jump.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.rocket_blitz_slot"), Config.ROCKET_BLITZ_SLOT, 0, 9).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ROCKET_BLITZ_SLOT)).setSaveConsumer(newValue -> {            Config.ROCKET_BLITZ_SLOT = newValue;        }).build());
        jump.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.rocket_trigger"), Config.RocketTrigger.class, Config.ROCKET_TRIGGER).setDefaultValue(Config.RocketTrigger.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ROCKET_TRIGGER))).setSaveConsumer(newValue -> {            Config.ROCKET_TRIGGER = newValue;        }).build());
        jump.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.jump_spam"), Config.JUMP_SPAM).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_JUMP_SPAM)).setSaveConsumer(newValue -> {            Config.JUMP_SPAM = newValue;        }).build());
        jump.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.jump_spam_tick"), Config.JUMP_SPAM_TICK, 2, 8).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_JUMP_SPAM_TICK)).setSaveConsumer(newValue -> {            Config.JUMP_SPAM_TICK = newValue;        }).build());
        jump.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Elytra Boost - Reflection Angle"), Config.REFLECTION_ANGLE, -60, -10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_REFLECTION_ANGLE)).setSaveConsumer(newValue -> {            Config.REFLECTION_ANGLE = newValue;        }).build());
        jump.addEntry(entryBuilder.startBooleanToggle((Text)Text.literal((String)"Jump Assist / Elytra Boost - Prioritize Use Wind Charge"), Config.PRIORITIZE_WIND_CHARGE).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_PRIORITIZE_WIND_CHARGE)).setSaveConsumer(newValue -> {            Config.PRIORITIZE_WIND_CHARGE = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.prioritize")}).build());
        jump.addEntry(entryBuilder.startBooleanToggle((Text)Text.literal((String)"Rocket Blitz - Prioritize Use Fireworks Rocket"), Config.PRIORITIZE_ROCKET).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_PRIORITIZE_ROCKET)).setSaveConsumer(newValue -> {            Config.PRIORITIZE_ROCKET = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.prioritize")}).build());
        refill.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.auto_refill"), Config.AUTO_REFILL).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_AUTO_REFILL)).setSaveConsumer(newValue -> {            Config.AUTO_REFILL = newValue;        }).build());
        effects.addEntry(entryBuilder.startEnumSelector((Text)Text.literal((String)"Target Marker Type"), Config.MarkerType.class, Config.MARKER_TYPE).setDefaultValue(Config.MarkerType.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_MARKER_TYPE))).setSaveConsumer(newValue -> {            Config.MARKER_TYPE = newValue;        }).build());
        effects.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.target_search_mode"), Config.TARGET_SEARCH_MODE).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_TARGET_SEARCH_MODE)).setSaveConsumer(newValue -> {            Config.TARGET_SEARCH_MODE = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.target_search_mode")}).build());
        effects.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.on_target"), Config.TARGET_MARKER).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_TARGET_MARKER)).setSaveConsumer(newValue -> {            Config.TARGET_MARKER = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.on_target")}).build());
        effects.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.hide_marker"), Config.HIDE_MARKER).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_HIDE_MARKER)).setSaveConsumer(newValue -> {            Config.HIDE_MARKER = newValue;        }).build());
        effects.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.marker_offset"), Config.MARKER_OFFSET, 0, 5).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_MARKER_OFFSET)).setSaveConsumer(newValue -> {            Config.MARKER_OFFSET = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.marker_offset")}).build());
        effects.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.on_weapon"), Config.WeaponParticle.class, Config.MACE_PARTICLE).setDefaultValue(Config.WeaponParticle.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_MACE_PARTICLE))).setSaveConsumer(newValue -> {            Config.MACE_PARTICLE = newValue;        }).build());
        effects.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.transition_threshold"), Config.PARTICLE_TRANSITION_THRESHOLD, 10, 20).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_PARTICLE_TRANSITION_THRESHOLD)).setSaveConsumer(newValue -> {            Config.PARTICLE_TRANSITION_THRESHOLD = newValue;        }).build());
        effects.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.particle_order"), Config.TransitionOrder.class, Config.PARTICLE_ORDER).setDefaultValue(Config.TransitionOrder.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_PARTICLE_ORDER))).setSaveConsumer(newValue -> {            Config.PARTICLE_ORDER = newValue;        }).build());
        recon.addEntry(entryBuilder.startEnumSelector((Text)Text.literal((String)"Recon View Perspective"), Config.ReconView.class, Config.ZOOM_VIEW).setDefaultValue(Config.ReconView.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ZOOM_VIEW))).setSaveConsumer(newValue -> {            Config.ZOOM_VIEW = newValue;        }).build());
        recon.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Zoom In/Out Step"), Config.ZOOM_STEP, 3, 10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_ZOOM_STEP)).setSaveConsumer(newValue -> {            Config.ZOOM_STEP = newValue;        }).build());
        recon.addEntry(entryBuilder.startBooleanToggle((Text)Text.literal((String)"Display Crosshairs When [THIRD_PERSON_BACK]"), Config.PERSPECTIVE_BACK_CROSSHAIR).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_PERSPECTIVE_BACK_CROSSHAIR)).setSaveConsumer(newValue -> {            Config.PERSPECTIVE_BACK_CROSSHAIR = newValue;        }).build());
        recon.addEntry(entryBuilder.startBooleanToggle((Text)Text.literal((String)"Set the current viewing direction when returning to normal state"), Config.CAMERA_RETURN_BEHAVIOR).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_CAMERA_RETURN_BEHAVIOR)).setSaveConsumer(newValue -> {            Config.CAMERA_RETURN_BEHAVIOR = newValue;        }).build());
        others.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"High Speed Input Mode"), Config.FALL_VELOCITY[0], 1, 56).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FALL_VELOCITY[0])).setSaveConsumer(newValue -> {            Config.FALL_VELOCITY[0] = newValue;        }).build());
        others.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.fov_suppression"), Config.FOV_SUPPRESSION).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FOV_SUPPRESSION)).setSaveConsumer(newValue -> {            Config.FOV_SUPPRESSION = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip_fov_suppression")}).build());
        others.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.flap_suppression"), Config.FLAP_SUPPRESSION).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FLAP_SUPPRESSION)).setSaveConsumer(newValue -> {            Config.FLAP_SUPPRESSION = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip_flap_suppression")}).build());
        others.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.flap_suppression_threshold"), Config.FLAP_SUPPRESSION_THRESHOLD, 5, 20).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FLAP_SUPPRESSION_THRESHOLD)).setSaveConsumer(newValue -> {            Config.FLAP_SUPPRESSION_THRESHOLD = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip_flap_suppression")}).build());
        others.addEntry(entryBuilder.startIntSlider((Text)Text.translatable((String)"config.mace_attack_assistance.option.flap_suppression_tick"), Config.FLAP_SUPPRESSION_TICK, 5, 20).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FLAP_SUPPRESSION_TICK)).setSaveConsumer(newValue -> {            Config.FLAP_SUPPRESSION_TICK = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip_flap_suppression")}).build());
        others.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.display_action_bar"), Config.DISPLAY_ACTION_BAR).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_DISPLAY_ACTION_BAR)).setSaveConsumer(newValue -> {            Config.DISPLAY_ACTION_BAR = newValue;        }).build());
        others.addEntry(entryBuilder.startBooleanToggle((Text)Text.translatable((String)"config.mace_attack_assistance.option.debug_screen"), Config.DEBUG_SCREEN).setDefaultValue(false).setSaveConsumer(newValue -> {            Config.DEBUG_SCREEN = newValue;        }).build());
        others.addEntry(entryBuilder.startTextDescription((Text)Text.literal((String)"\nCaution!").formatted(Formatting.BOLD).formatted(Formatting.YELLOW)).build());
        others.addEntry(entryBuilder.startBooleanToggle((Text)Text.literal((String)"Extreme Mode"), Config.EXTREME).setDefaultValue((Boolean)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_EXTREME)).setTooltip(new Text[]{Text.literal((String)"New functions have been added to the conventional attack processing, providing even greater attack performance.")}).setSaveConsumer(newValue -> {            Config.EXTREME = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Spiral Count"), Config.SP_SPIRAL_COUNT, 1, 10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SPIRAL_COUNT)).setSaveConsumer(newValue -> {            Config.SP_SPIRAL_COUNT = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Spiral Length"), Config.SP_SPIRAL_LENGTH, 1, 40).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SPAIRAL_LENGTH)).setSaveConsumer(newValue -> {            Config.SP_SPIRAL_LENGTH = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Spiral Alpha"), Config.SP_SPIRAL_ALPHA, 1, 10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SPIRAL_ALPHA)).setSaveConsumer(newValue -> {            Config.SP_SPIRAL_ALPHA = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Spiral Gamma"), Config.SP_SPIRAL_GAMMA, 10, 50).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SPIRAL_GAMMA)).setSaveConsumer(newValue -> {            Config.SP_SPIRAL_GAMMA = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Coils"), Config.SP_COILS, 1, 8).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_COILS)).setSaveConsumer(newValue -> {            Config.SP_COILS = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Height"), Config.SP_HEIGHT, 1, 10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_HEIGHT)).setSaveConsumer(newValue -> {            Config.SP_HEIGHT = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Size"), Config.SP_SIZE, 1, 10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SIZE)).setSaveConsumer(newValue -> {            Config.SP_SIZE = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Speed"), Config.SP_SPEED, 1, 50).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_SPEED)).setSaveConsumer(newValue -> {            Config.SP_SPEED = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Base Radius"), Config.SP_BASE_RADIUS, 1, 10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_BASE_RADIUS)).setSaveConsumer(newValue -> {            Config.SP_BASE_RADIUS = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Wave Speed"), Config.SP_WAVE_SPEED, 1, 80).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_WAVE_SPEED)).setSaveConsumer(newValue -> {            Config.SP_WAVE_SPEED = newValue;        }).build());
        spiral.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Wave Amplitude"), Config.SP_WAVE_AMPLITUDE, 1, 8).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_WAVE_AMPLITUDE)).setSaveConsumer(newValue -> {            Config.SP_WAVE_AMPLITUDE = newValue;        }).build());
        color.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_villager"), ColorData.Color.class, Config.COLOR_VILLAGER).setDefaultValue(ColorData.Color.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_COLOR_VILLAGER))).setSaveConsumer(newValue -> {            Config.COLOR_VILLAGER = newValue;        }).build());
        color.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_hostile"), ColorData.Color.class, Config.COLOR_HOSTILE).setDefaultValue(ColorData.Color.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_COLOR_HOSTILE))).setSaveConsumer(newValue -> {            Config.COLOR_HOSTILE = newValue;        }).build());
        color.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_warden"), ColorData.Color.class, Config.COLOR_WARDEN).setDefaultValue(ColorData.Color.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_COLOR_WARDEN))).setSaveConsumer(newValue -> {            Config.COLOR_WARDEN = newValue;        }).build());
        color.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_iron_golem"), ColorData.Color.class, Config.COLOR_IRON_GOLEM).setDefaultValue(ColorData.Color.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_COLOR_IRON_GOLEM))).setSaveConsumer(newValue -> {            Config.COLOR_IRON_GOLEM = newValue;        }).build());
        color.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_passive"), ColorData.Color.class, Config.COLOR_PASSIVE).setDefaultValue(ColorData.Color.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_COLOR_PASSIVE))).setSaveConsumer(newValue -> {            Config.COLOR_PASSIVE = newValue;        }).build());
        color.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_ambient"), ColorData.Color.class, Config.COLOR_AMBIENT).setDefaultValue(ColorData.Color.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_COLOR_AMBIENT))).setSaveConsumer(newValue -> {            Config.COLOR_AMBIENT = newValue;        }).build());
        color.addEntry(entryBuilder.startEnumSelector((Text)Text.translatable((String)"config.mace_attack_assistance.option.allowed_player"), ColorData.Color.class, Config.COLOR_PLAYER).setDefaultValue(ColorData.Color.valueOf((String)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_COLOR_PLAYER))).setSaveConsumer(newValue -> {            Config.COLOR_PLAYER = newValue;        }).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.dark_blue).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.dark_green).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.dark_aqua).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.dark_red).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.dark_purple).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.gold).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.gray).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.dark_gray).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.blue).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.green).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.aqua).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.red).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.light_purple).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.yellow).build());
        color.addEntry(entryBuilder.startTextDescription((Text)ColorData.white).build());
        fov.addEntry(entryBuilder.startTextDescription((Text)Text.translatable((String)"config.mace_attack_assistance.option.desc_fov").formatted(Formatting.BOLD).formatted(Formatting.GREEN)).build());
        fov.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"FOV X (Horizontal) * 10 degree [Gliding , Target Search: On]"), Config.FOV_HORIZONTAL, 1, 36).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FOV_HORIZONTAL)).setSaveConsumer(newValue -> {            Config.FOV_HORIZONTAL = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.fov_horizontal")}).build());
        fov.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"FOV Y (Vertical) * 10 degree [Gliding , Target Search: On]"), Config.FOV_VERTICAL, 1, 18).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FOV_VERTICAL)).setSaveConsumer(newValue -> {            Config.FOV_VERTICAL = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.fov_vertical")}).build());
        fov.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"FOV X (Horizontal) * 10 degree [Recon Camera Mode]"), Config.FOV_HORIZONTAL_ON_ZOOM, 1, 36).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FOV_HORIZONTAL_ON_ZOOM)).setSaveConsumer(newValue -> {            Config.FOV_HORIZONTAL_ON_ZOOM = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.fov_horizontal")}).build());
        fov.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"FOV Y (Vertical) * 10 degree [Recon Camera Mode]"), Config.FOV_VERTICAL_ON_ZOOM, 1, 18).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_FOV_VERTICAL_ON_ZOOM)).setSaveConsumer(newValue -> {            Config.FOV_VERTICAL_ON_ZOOM = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.fov_vertical")}).build());
        fov.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Rectangle Horizontal * 10 blocks"), Config.RADAR_HORIZONTAL, 1, 5).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_RADAR_HORIZONTAL)).setSaveConsumer(newValue -> {            Config.RADAR_HORIZONTAL = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.radar_horizontal")}).build());
        fov.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Rectangle Upward * 10 blocks"), Config.RADAR_UPWARD, 1, 3).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_RADAR_UPWARD)).setSaveConsumer(newValue -> {            Config.RADAR_UPWARD = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.radar_upward")}).build());
        fov.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Rectangle Downward * 10 blocks"), Config.RADAR_DOWNWARD, 1, 8).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_RADAR_DOWNWARD)).setSaveConsumer(newValue -> {            Config.RADAR_DOWNWARD = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.radar_downward")}).build());
        fov.addEntry(entryBuilder.startIntSlider((Text)Text.literal((String)"Rectangle Update Interval"), Config.RADAR_UPDATE_INTERVAL, 1, 10).setDefaultValue((Integer)ModConfigScreen.getDefaultValue(ConfigOperation.PROP_RADAR_UPDATE_INTERVAL)).setSaveConsumer(newValue -> {            Config.RADAR_UPDATE_INTERVAL = newValue;        }).setTooltip(new Text[]{Text.translatable((String)"config.mace_attack_assistance.option.tooltip.radar_update_interval")}).build());
        ConfigCategory friends = builder.getOrCreateCategory((Text)Text.literal((String)"Friends"));
        friends.addEntry(entryBuilder.startTextDescription((Text)Text.literal((String)"Players added to this list will never be targeted by any combat feature.").formatted(Formatting.GRAY)).build());
        List<String> currentFriends = new ArrayList<>(com.papack.maceattackassistance.client.FriendManager.getFriends());
        friends.addEntry(entryBuilder.startStrList((Text)Text.literal((String)"Friend List"), currentFriends).setDefaultValue(new ArrayList<>()).setSaveConsumer(newValue -> {
            List<String> filtered = new ArrayList<>();
            java.util.Set<String> seen = new java.util.HashSet<>();
            for (String name : newValue) {
                String trimmed = name.trim();
                if (!trimmed.isEmpty() && seen.add(trimmed.toLowerCase(java.util.Locale.ROOT))) {
                    filtered.add(trimmed);
                }
            }
            Config.FRIENDS = filtered;
            com.papack.maceattackassistance.client.FriendManager.setFriends(filtered);
        }).setTooltip(new Text[]{Text.literal((String)"Enter Minecraft usernames. Duplicate and empty entries are removed automatically.").formatted(Formatting.GRAY)}).build());
        builder.setSavingRunnable(ConfigOperation::saveFile);
        return builder.build();
    }

    public static Object getDefaultValue(ConfigOperation.ConfigData configData) {
        switch (configData.type()) {
            case I: {
                return Integer.parseInt(configData.defaultValue());
            }
            case B: {
                return Boolean.parseBoolean(configData.defaultValue());
            }
        }
        return configData.defaultValue();
    }
}
